### ISSUE TITLE
Errors in the Console are causing more not to be able to enter play mode in Unity

### ISSUE THREAD

**Issue by isaacwalkercox** [leapmotion/UnityModules#1060] opened 2018-10-03 17:46 UTC
I am receiving these errors which are causing me not to be able to enter play mode in Unity.

> Shader error in 'LeapMotion/Passthrough/Foreground': failed to open source file: 'Assets/LeapMotion/Core/Resources/LeapCG.cginc' at line 15 (on d3d11)
> 
> Compiling Vertex program with LEAP_FORMAT_IR
> Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR
> 
> 
> Shader error in 'LeapMotion/Passthrough/Background': failed to open source file: 'Assets/LeapMotion/Core/Resources/LeapCG.cginc' at line 11 (on d3d11)
> 
> Compiling Vertex program
> Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR
> 
> 
> 
> Shader error in 'LeapMotion/Passthrough/ThresholdOverlay': failed to open source file: 'Assets/LeapMotion/Core/Resources/LeapCG.cginc' at line 22 (on d3d11)
> 
> Compiling Vertex program with LEAP_FORMAT_IR
> Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR
> 
> 
> 
> CreateAsset: Cannot create Assets with relative path!
> UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
> 
> 
> Assets/Modules/GraphicRenderer/Testing/Scripts/SetupGraphicRendererTests.cs(15,18): error CS0234: The type or namespace name `Testing' does not exist in the namespace `Leap.Unity'. Are you missing an assembly reference?
>

**Comment by nickjbenson** [comment] 2018-10-11 22:28
What is your Unity version and what version of UnityModules are you using? I need to be able to reproduce the issue to look into a fix.

However, just looking at these issues, I'm suspicious of your folder placement. Is your `LeapMotion` folder inside a nested folder, and not in your root `Assets` directory?

**Comment by isaacwalkercox** [comment] 2018-10-11 22:41
I am using 2018.2 and the folder is in the root of the Assets folder. 

Thank you.

**Comment by nickjbenson** [comment] 2018-10-11 22:43
Did you clone the `master` branch or did you download the latest releases via unitypackages from our developer page?

Both are intended to work, although the unitypackages from our developer page are more stable, in exchange for a slower feature-rollout. I just need to know so I can reproduce your environment.

**Comment by isaacwalkercox** [comment] 2018-10-11 22:53
I did both. They both had individual problems but the console errors I believe relate to the developer page package. I may be wrong though, I am not in a position to confirm it. 

⁣Sent from TypeApp ​

**Comment by nickjbenson** [comment] 2020-04-30 01:28
Circling back, I believe this was caused by an assembly definitions issue that has been addressed in 4.5.0. If the problem persists, please re-open the issue.

**Closed by nickjbenson** 2020-04-30 01:28 UTC
