### ISSUE TITLE
Creating a new Controller object hangs Unity editor [Workaround within. Fixed in next release.]

### ISSUE THREAD

**Issue by jo3w4rd** [leapmotion/UnityModules#473] opened 2016-12-09 01:27 UTC
Simply executing:

    Controller controller = new Controller();

Seems to be enough to hang the Unity editor (>50% of the time), even in a scene that does not already have a controller object. The project works fine otherwise, using the Orion Unity assets. Given that we do successfully create a new Controller object in the Orion assets, it is hard to say why this would hand the editor. Possibly a timing issue? This happens in the current, public release (4.1.4) as well as the tip of develop.

**Comment by Amarcolina** [comment] 2016-12-09 01:42
LeapServiceProvider has dedicated code to destroy the controller when the provider gets destroyed (which happens whenever you exit play mode).  My guess is that there is nothing that prevents the worker thread from stopping, which makes unity sad.

**Comment by jo3w4rd** [comment] 2016-12-09 01:45
This never gets as far as exiting -- it hangs right after pressing play.

**Comment by Amarcolina** [comment] 2016-12-09 01:48
Make sure you restart Unity before testing.  If worker threads are left over, pressing play might reveal an issue that was created from a previous run.  When I try, things work fine the first time I press play without a crash/hand on exit.  When i press play the second time, that is when I get the hang.

**Comment by jo3w4rd** [comment] 2016-12-09 01:48
The problem itself made that a necessity -- I had to force-kill Unity every time.

**Comment by Amarcolina** [comment] 2016-12-09 01:49
That is very strange then, since I cannot replicate it o.O

**Comment by Amarcolina** [comment] 2016-12-09 01:53
We should get everybody a copy of this asset, it can be very useful to diagnose issues like this.  
https://www.assetstore.unity3d.com/en/#!/content/40167
I'll take a look and see if I can figure out what is causing the freeze.

**Comment by jo3w4rd** [comment] 2016-12-14 20:06
As a workaround, you can drop a LeapHandController prefab into the scene and access frames using this script:


    using UnityEngine;
    using Leap;
    using Leap.Unity;
    using Leap.Unity.Attributes;

    public class TestAddedController : MonoBehaviour {

      [AutoFind]
      public LeapServiceProvider provider;

    void Update () {
        Frame frame = provider.CurrentFrame;
        if(frame != null) {
          foreach(Hand hand in frame.Hands) {
            Vector3 handPosition = hand.PalmPosition.ToVector3();
          }
        }
    }

**Comment by nickjbenson** [comment] 2017-06-19 23:03
Closing since we could not reproduce. If someone reports the issue we can investigate further.

**Comment by SteffenItterheim-Pixomondo** [comment] 2018-01-29 15:22
Someone here. ;)

We've been having this issue since integrating LeapMotion last year. In the meantime we switched from Unity 5.6 to 2017.3 and upgraded the Leap Motion SDK to the latest but the issue persists. 

To improve stability, we had to and still have to untick all "platforms" checkboxes for the LeapC.dll file in Unity for all developers who are currently not working with the Leap (there were also issues with Leap Motion integration while Leap is not connected, such as terribly slow debugging).

To enable this, we swallow the DLLNotFoundException in the Awake() method:

```
            try
            {
                s_leapController = new Leap.Controller();
            }
            catch (System.DllNotFoundException)
            {
                Debug.LogWarning("LeapC.Dll not found ==> LEAP MOTION SUPPORT IS DISABLED! <== (this may be on purpose cause Leap Motion SDK tends to crash Unity)");
            }
```
While in OnDestroy() we shut down the controller (if connected):
```
        void OnDestroy()
        {
            if (s_leapController != null)
            {
                if (s_leapController.IsConnected)
                {
                    s_leapController.ClearPolicy(Leap.Controller.PolicyFlag.POLICY_OPTIMIZE_HMD);
                    s_leapController.StopConnection();
                }
                s_leapController = null;
            }
        }
```

I would like you to re-open this issue. If you have any debug builds that would help to narrow down the issue we'd be happy to help - anything to end this crash-happy madness.

**Comment by SteffenItterheim-Pixomondo** [comment] 2018-01-29 15:56
I suspect LeapVRTemporalWarping to be the root of the issue. One may or may not have this script active. When it is active, it tries to create a controller every frame. When you create your own instance of the controller manually, bypassing LeapServiceProvider, you end up creating two instances of LeapController and possibly shutting down only one of them.

**Comment by Amarcolina** [comment] 2018-01-30 02:31
Could you describe the specific steps needed to reproduce this issue?  Does this, for example, happen in any of the example scenes packaged in the Core module?  Or does it require some specific scripts of your own to be present in the scene?

**Comment by Blacklands** [comment] 2018-02-08 05:03
This happens to me too, and I found a fix(?) just by today.

I have: Unity 2017.3.0f3, and the latest versions of all the Leap Motion assets that can be downloaded on the [developer page](https://developer.leapmotion.com/unity).
To reproduce, for me it is enough to create an entirely new Unity project, import all the assets (I'm using all of them currently), and have any script create a new `Controller` object, just like in the first post:
```Controller controller = new Controller();```

What I found:
The freeze happens consistently on two occasions: Entering and existing play mode for the first time works fine, and everyone before doing this works fine too. After this, Unity will freeze forever when:
- Play mode is entered another time (it freezes right away after clicking on the "play" symbol)
- Unity compiles scripts (so, changing any script code in the IDE you use, to trigger a re-compile); it freezes midway through the compilation (as indicated by the little rotating progress indicator in the bottom right corner)

I first checked the Unity log file. On both occasions, the last line in the log before the freeze was:
```Begin MonoManager ReloadAssembly```

I suspected that there is some unmanaged resource that isn't released automatically by `Controller`, and that makes Unity freeze when it tries to access the resource for a second time, or something like this.
I saw that `Controller` implements `IDisposable`, so I tried to call
```controller.Dispose();```
in Unity's `OnDestroy()`, which did not help at all (no observable changes to the problem).

**What finally ended up fixing it for me** is calling
```controller.StopConnection()```
sometime (I did it in `OnDestroy()`) before/while play mode is stopped. Now, everything seems to work fine again.
As the constructor of `Controller` starts a connection automatically, afaik, this mysterious connection seems to be the problem? It seems it is not close, and Unity is not able/does not attempt to close it either, when play mode is existed (I don't know much at all about the internals of Unity; maybe it is normal that it does not).

This is all I have so far on the issue.

**Comment by Amarcolina** [comment] 2018-02-08 18:03
That is an accurate description of the source of the problem, as well as the (temporary) fix!  Unity is indeed trying to close the worker thread that handles the connection, which it cannot do until the connection is closed.

For now, the close connection workaround will be the one I will be recommending.  But we have also fixed this on our internal repository, which will be included in the next release, which will autoclose the connection when the assembly is unloaded.  

I'll keep this issue open for now, until that release goes out.

**Comment by SteffenItterheim-Pixomondo** [comment] 2018-02-12 08:14
I read from this that in the meantime we can set up an editor script and sign up to OnBeforeAssemblyReload (sp?) event, in order to call CloseConnection before assemblies are being un-/re-loaded. We'll give this a try.

**Comment by nickjbenson** [comment] 2018-06-11 18:17
Hey everyone, Core 4.4.0 has been released, and with it, this bug should be resolved.

I'm going to close the issue, but if we see it crop up again, please comment and we can start a new investigation.

**Closed by nickjbenson** 2018-06-11 18:17 UTC
Labels: bug
