### ISSUE TITLE
Android FPS counter continues to climb when the device is disconnected

### ISSUE THREAD

**Issue by testmasterbright** [leapmotion/UnityModules#253] opened 2016-05-25 21:20 UTC
The Android Data FPS counter in OrionHMD continues to climb into the extreme positive/negative anytime the controller is disconnected.

I believe this is in the Unity code. We have another app (HandsOnlyCardboard) that just halts the FPS counter on the last value when it disconnects.

It should drop to zero when it cannot detect the device.

![screenshot_20160525-141647](https://cloud.githubusercontent.com/assets/6034882/15556575/5b0203c6-2283-11e6-9e3d-deb20f60f277.png)

**Comment by testmasterbright** [comment] 2016-05-25 21:24
@hham @veronicaz41 @jdonald I wasnt sure who this would go to. Please feel free to reassign it.

**Comment by jdonald** [comment] 2016-06-01 23:13
@protodeep would someone from your side be able to look at this and perhaps it's a quick fix?

The power stuff that Hyoung and Veronica are doing next take priority over this bugfix, and so if Frontend is swamped this can wait. Not a huge deal for Baofeng.

**Comment by Amarcolina** [comment] 2016-06-01 23:52
As far as I can see, the framerate it just copied directly out of LeapC, so it wouldn't be a fix in the asset side nor the csharp wrapper.  One thing to notice however is that it only happens when interpolation is turned on, so it might be related.  @jhe- might be able to give more insight.

**Comment by nickjbenson** [comment] 2017-06-19 22:51
@testmasterbright Suggesting closing this since we're pretty convinced it's not on Unity side and the issue is pretty stale.

**Comment by Amarcolina** [comment] 2017-06-19 22:54
We figured out the issue IIRC.  It was just that when tracking is unplugged it causes Unity to ask for an interpolated time that is progressively further the most recent frame.  Consequently the FPS is extrapolated based on the most recent two frames, causing it to appear to rise or fall at a constant rate.  Basically the same effect you see when the hands float away, but with FPS!

Really needs to be fixed on the API side since the Unity side is less aware of which frames are available to interpolate.  Could be simply fixed by not interpolating the FPS at all, it's not really a param that requires interpolation! :D

**Closed** 2017-06-21 17:57 UTC
Labels: bug
