### ISSUE TITLE
Destroying an anchored GameObject

### ISSUE THREAD

**Issue by radiodario** [leapmotion/UnityModules#742] opened 2017-06-16 09:02 UTC
Hi there, 

I´m trying to make a menu where if you touch an InteractionBehaviour, a gameobject is spawned, but only the user has touched the gameobject for a while. This means i´m spawning the object right away and then starting a coroutine that grows the object to a desired scale. If the user leaves the touch area before the coroutine is done, I delete the object. The problem is that if i destroy the gameobject, I get a lot of errors from the Interaction Manager.

Is there a proper procedure to destroy an anchored GameObject? I´ve tried dettaching and deactivating before destroying, but i still get reference errors.

thanks!

**Comment by nickjbenson** [comment] 2017-06-16 15:12
Hi Dario,

Can you paste the error you're getting? Could be a registration error but I need the error text to diagnose further.

**Comment by nickjbenson** [comment] 2017-07-06 00:07
Hey Dario,

I'm going to close this issue because I haven't gotten reproduction steps from you; it should be possible to delete InteractionBehaviours without error but I need more specifics to reproduce the error you're getting if there's still a problem.

If the error is on our end please feel free to respond back and I'll re-open the issue so we can investigate more.

**Closed by nickjbenson** 2017-07-06 00:07 UTC
