### ISSUE TITLE
AnchorGroup/SerializableHashset throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by julienkay** [leapmotion/UnityModules#893] opened 2017-10-13 15:33 UTC
First error:
IndexOutOfRangeException: Array index is out of range.
System.Collections.Generic.HashSet`1[T].Add (.T item)
Leap.Unity.SerializableHashSet`1[T].OnAfterDeserialize () (at Assets/LeapMotion/Core/Scripts/DataStructures/SerializableHashSet.cs:74)
UnityEditor.HostView:OnGUI()

and after that continuously:
IndexOutOfRangeException: Array index is out of range.
System.Collections.Generic.HashSet`1[T].GetLinkHashCode (Int32 index)
System.Collections.Generic.HashSet`1+Enumerator[Leap.Unity.Interaction.Anchor].MoveNext ()
Leap.Unity.SerializableHashSet`1[T].OnBeforeSerialize () (at Assets/LeapMotion/Core/Scripts/DataStructures/SerializableHashSet.cs:103)
UnityEditor.HostView:OnInspectorUpdate()

To reproduce I'd suggest trying the following (I'm not exactly sure adding a lot of Anchors is the only reason this happens)

1.) Open the Anchors scene of the InteractionEngine examples
2.) Duplicate an Anchor (e.g. the Red Vive Anchor) about 10-20 times
3.) Select an AnchorGroup (e.g. Red Anchor Group) and add all the duplicated Anchors

This should already log the error above. When building an application (and sometimes also when you enter/exit playmode) the changes made to the AnchorGroup are lost.

**Comment by Amarcolina** [comment] 2017-10-17 00:27
Does this happen using the latest develop?  I am currently unable to reproduce the error with the given steps.  Are you running under any specific execution settings?  Are you using the 4.6 Net api?  Specific build target?

**Comment by dyanikoglu** [comment] 2017-10-17 06:42
I can confirm that this problem occurs when you use 4.6 Net API. I have faced same problem before, after switching back to 3.5 API, these exceptions gone away.

**Comment by julienkay** [comment] 2017-10-17 11:54
I tested with the latest public release as well as the latest master.(18a0dccd97e1da497282e0d9d2ca9a0303d18480)
For me this also happens with the Mono2x Scripting Backend (I'm actually still on Unity 5.6)

I can check if this also happens for me on 2017.2 with different configurations. I'll report back later.

**Comment by Amarcolina** [comment] 2017-10-17 18:08
@julienkay how do you go about adding all of the new anchors after duplication?  Do you manually press the + button in the inspector, drag in the anchor, and repeat?  Or do you do it a different way?

**Comment by julienkay** [comment] 2017-10-17 19:35
So I just tested this on 2017.2.0f3 and the latest develop and it happens there too. All settings are default (.NET 3.5)

I manually press the + button, then I select the little circle (Property Picker?) and choose the next of the duplicated Anchors in the scene. When I've done that a few times I save the scene. Then I start PlayMode. This already logs the first error. After that I do a Build and when reselecting the AnchorGroup afterwards the changes are lost and the second error keeps getting logged in the console.

**Comment by Amarcolina** [comment] 2017-10-17 20:06
Ah got it, was able to replicate 👍 so strange....  worried that this might be a Unity bug, since the error happens _inside the HashSet implementation_ which means that Unity is messing up the serialized representation of the hash set.

Will continue to investigate, hopefully there is a good solution.

**Comment by Amarcolina** [comment] 2017-11-06 18:10
So posting here as an update.  I confirmed through some testing that when Unity serializes and then deserializes the fields of the hash set, it leaves it in an _invalid_ state that doesn't seem to be able to be fixed by calling Clear or any other methods.  

It seems that the strategy of inheriting directly from HashSet might not be possible, which is unfortunate.  There is a straightforward solution, which is to embed the HashSet as a _field_ inside of the new type, and then create a duplicate copy of every method and property that is just directly connected to the hash set field.  This is pretty inelegant, but might be our only option :( I'll keep you guys posted.

**Comment by Amarcolina** [comment] 2018-02-27 23:26
Update, took the time to dive into the reflected code that backs HashSet and Dictionary.  Turns out the underlying implementation changed in Net4.5 to use fields that were not directly serializable by unity anymore, causing the serialization to only work for half of the data structure, leaving it in an invalid state.

The fix is a bit of a brute force approach, but all issues should be fixed.  Only downside is that SerializableHashSet is no longer actually a subclass of HashSet, it just has a lot of the same methods and can be implicitly converted.

**Comment by Amarcolina** [comment] 2018-03-01 02:00
Alright this issue has been resolved and has been merged into develop!  Develop currently contains a bunch of extra changes that are not the friendliest for backwards compatibility, so I'll also look to creating a hotfix branch to specifically move these changes into master as well so that people who need to upgrade can do so.

**Closed by Amarcolina** 2018-03-01 02:00 UTC
Labels: bug
