### ISSUE TITLE
Physics hands separate from graphics hands

### ISSUE THREAD

**Issue by jo3w4rd** [leapmotion/UnityModules#50] opened 2016-03-08 01:19 UTC
See this post: https://community.leapmotion.com/t/unity3d-orion-rigidhand-not-following-capsulehand-during-movement/4780

> "I have a project setup where I interact with the controls inside of a spaceship using Orion. 
> Problem is that the RigidHand hitbox does not follow the model of the hand as it should when the ship starts moving forward.
> 
> When the ship is idle everything works perfectly, but as soon as it starts moving, the RigidHand always drags up behind. Problem is probably due to a simple timing between updating the model of the hand and its hitboxes."

**Comment by jo3w4rd** [comment] 2016-03-08 03:24
Might be related to (or even the same as) #3.

**Comment by Amarcolina** [comment] 2016-03-08 03:44
@protodeep  and I discovered that it might simply be caused due to physics framerate being lower than render framerate.  When physics framerate is turned up higher than render framerate the judder and lag goes away completely.

**Comment by Amarcolina** [comment] 2016-03-08 04:27
Upon further investigation it also looks like setting the rigidbody's interpolation setting to None improves the behavior significantly, even without any core asset upgrades.  This might be something we can recommend to developers before the next release?

**Comment by Amarcolina** [comment] 2016-03-09 03:31
Has been addressed by #58, and is only a minor issue right now.  I am going to close out this issue because if there is anything else that needs to improve registration it will be caused by different issues

**Closed by Amarcolina** 2016-03-09 03:31 UTC
Labels: bug
